### ISSUE TITLE
Uploading/Recording HD video did not transform to SD even if is configured 

### ISSUE THREAD

**Issue by milosmoto** [Ziggeo/react-ziggeo#17]
Hi @sambua  @Bane-D ,

There is one issue with uploading(not sure about recording), when you upload HD video it will upload and save HD video even if we configure smaller resolution with recorder parameters:
recordingwidth
recordingheight

Thanks
Milos Milojevic

**Comment by Bane-D** [comment]
Hi Milos,

`recordingwidth` and `recordingheight` will set up the width and height of the recording, during recording and only if possible (some cameras do not allow you to set this up for example or might prefer a different approximate resolution to be used instead).

Now since you say uploading - we will actually not change anything during the upload since that would require browsers to be able to:
1. load entire video file into memory
2. allow re-encoding of the video within the browser
3. generate a new file and then upload that one

For this reason I do not think that any browser will support something like that any time soon, as this requires having some additional services available on the system itself.

So to summarize:
1. Uploading file means that it will not respect recording related parameters
2. uploading is only limited by uploading parameters (such as size,extensions and alike)
3. file will always be uploaded as is (only once it is on our servers can we know if this is a very long SD file or a very short 4K file)

Now going further we never change the original video, so it will always stay as is within the original stream. You can however convert it to any other resolution you want by using our video profiles.

**Info**
* Video profiles must be created on in your application first, where you set it up for resolution you want to have and if going through expert settings you can fine tune how scaling up or down the video would work - the strategy that would be used).
* using token or key of the video profile any video uploaded through embedding with that video profile set up on it will result in the new streams being created as per video profile.

Hope that helps,
Bane
