### ISSUE TITLE
Question audio transcritpion

### ISSUE THREAD

**Issue by milosmoto** [Ziggeo/react-ziggeo#23]
Hi @Bane-D ,

Sorry lost your email, that's why I am sending question here. Can you provide video/audio transcription with API or with some webhook. Also is it possible to do that for old record?

Found some article:

https://support.ziggeo.com/hc/en-us/articles/115000801488-How-to-setup-and-see-audio-transcription

Kind regards
Milos Milojevic

**Comment by Bane-D** [comment]
Hi Milos,

All is good. We have our support email support@ziggeo.com for anything that should be asked in private, or you can change it to "bane" for my own email, if you want to get in touch directly :)

> Can you provide video/audio transcription with API or with some webhook

Both actually.

You would get audio transcription any time you get video data. So index() function or get() would return this data for you.

We also have a webhook that can provide you with the info as it becomes available. You would see the list here: https://ziggeo.com/docs/api/webhooks/list

`video_transcription` and `video_transcription_failed` would be of use.

PS: The reason why the failed one would fire would be if you upload a video without audio stream (not the silent audio, rather video data without audio data). Otherwise the first one would fire.

>Also is it possible to do that for old record?

Yes. Regardless when audio transcription was made, the data is always attached to it so you can retrieve it at any point in time.

Possibly interesting depending on the purpose of the same - subtitles are going to be part of our r31 release which are based on the audio transcription.

Regards,
Bane
