### ISSUE TITLE
"onlyaudio" param return "cannot access this video" error.

### ISSUE THREAD

**Issue by highlabs** [Ziggeo/react-ziggeo#31]
Hi again! :)

I'm trying to use react-ziggeo (3.1.1), to record only audio, but I'm getting "We cannot access this video at the moment. Please try again later." error.

Screenshots: https://imgur.com/a/CMMEMg4

In Dashboard > Videos > Failed I found this response: https://pastebin.com/B1Js9TZL

Do you know whats happening?

**Comment by sambua** [comment]
Hello @highlabs :),

Thanks for the info, will check and revert soon.

**Comment by highlabs** [comment]
@sambua any news?

**Comment by sambua** [comment]
Hello @highlabs,

We're working on this issue, should be fixed during this week. Sorry, that not informed you before.

Thanks

**Comment by sambua** [comment]
Hello @highlabs ,

Sorry, it took some time while I respond to you. This bug is fixed on our `ziggeo-client-sdk` `2.33` latest version, but as it's not the stable version we can't upgrade `react-ziggeo` for all users.

If you want you can do it from your side, clone this repo, upgrade in package.json `"ziggeo-client-sdk": "~2.33.1"` version in `dependencies` and run `npm run build`.

If any questions please contact us.

Thanks.

**Comment by sambua** [comment]
Hello @highlabs ,

We've upgraded to the version where `onlyaudio` should be fixed with merge #36

**Comment by highlabs** [comment]
Hello,
We have tested the current latest version and the problem mentioned above is solved.
But on mobile the user is asked to use the camera app when recording audio. So a video is recorded and sent. The video is accepted even when `onlyaudio` is `true`. This is not the correct behaviour, right? (video being accepted when it is specified that should be only audio)

**Comment by Bane-D** [comment]
Great to hear that it is working.

In regards to the audio only, there is no actual validation if the video is included or not, it is just that the preference for recording is audio only.

We will be releasing a new version of audio only soon at which time you would be able to switch to it. That version would not accept the video.
