### ISSUE TITLE
How to prevent iPhone default recorder to load instead of Ziggeo's ?

### ISSUE THREAD

**Issue by bymoe** [Ziggeo/react-ziggeo#63]
When the user starts recording from iPhone the default recorder appear instead of recording using Ziggeo on the website. I do have `webrtc_on_mobile` to set to `{true}`.

In my user case, The user has to record using ziggeo and prevent any Phone defaults to appears.

Any help?

**Comment by Bane-D** [comment]
Hi there,

The webrtc_on_mobile will turn on WebRTC on mobile device as the name suggests, however Safari made a different implementation of WebRTC, or to say it differently they only made WebRTC Streaming implementation and offer it as WebRTC.

So to use WebRTC in such cases where it is yet is not available you should add `webrtc_streaming_if_necessary={true}`

Once you do, if WebRTC is available it will work, otherwise it will go with a fallback to the native camera app.

Hope this helps :)

**Comment by bymoe** [comment]
Thank you @Bane-D, `webrtc_streaming_if_necessary={true}` solved it.
