### ISSUE TITLE
Verifying failed on iPhone when using webrtc_streaming_if_necessary

### ISSUE THREAD

**Issue by bymoe** [Ziggeo/react-ziggeo#66]
As you can see here,
![failed](https://user-images.githubusercontent.com/20565199/87147462-5b02ca00-c2b5-11ea-808e-d66fb136a8e5.jpg)
I got this error only on iPhone & I am using `webrtc_streaming_if_necessary={true}`.
Desktop + Android is fine.

**Comment by Bane-D** [comment]
Can you please also use `webrtc_on_mobile={true}` as well?

In general the error would mean that our servers checked the video file and that it would not be possible to process it.

This can be caused by different reasons, however most likely would be if the video was not uploaded properly or damaged.

For example with streaming, if your video is under 10 second, that could be the cause of it. The iOS uses specific type of WebRTC recording - the WebRTC Streaming. What streaming does is to push the video segments to different servers, then sync them back into a single video. There is some random length of time that is needed to sync these videos and can be from 2 to 10 seconds depending on the video itself. If the data does not get sync and you already finalize the video, then there is just a second or two of the data that makes no sense, and can not be processed.

You would usually see Skype or other such apps to start your camera (for example red light is shown) and then for few moments you see a black screen or loading, etc. During this time the video and audio is being synced so their servers know where to merge different streams of data into one. This is the same, we just do not show the black screen while doing this :)

So do add the `webrtc_on_mobile` as mentioned above and try to record a video longer than 10 seconds and it I am sure it will work just fine for you :)

Regards,
Bane

**Comment by bymoe** [comment]
Thank you @Bane-D, I do already have `webrtc_on_mobile`.

You're right, All my testings was me recording for 1-2 seconds, I've tried with 10+ and It's working just fine. 
Thank you.
