### ISSUE TITLE
I cannot stop recording, Control bar not showing on iPhone

### ISSUE THREAD

**Issue by bymoe** [Ziggeo/react-ziggeo#67]
Just another iPhone issue with Ziggeo,
As you can see here: https://imgur.com/a/aluzWx0.

The control bar is completely hidden on iPhone; I cannot stop the video.
I've tested on Android and PC for the same build it works just fine.

Edit:
It's not a mobile responsive issue.

**Comment by Bane-D** [comment]
Hi there,

The good and the bad would be brought by CSS. Our system is designed to be easily modified by your codes, which can lead to intentional customization as well as to have some codes that change it in such way that something is not shown - like in your case.

My suggestion would be to try and remove the CSS that you have on the page that is specific to iOS. This would allow you to quickly confirm the same.

Now if you can not find the one that is causing it, and you can share the link for us to check, it would allow us to see which one might be causing it.

Regards,
Bane

**Comment by bymoe** [comment]
Hey @Bane-D,

I did remove my custom CSS and it turns out on iPhone it didn't even start recording, It's stuck on Loading as you can see here: https://imgur.com/a/RERNtNS.
If you would like to try live [Click here](https://domaintestaccount.elevatustesting.xyz/video/assessment/eyJpdiI6IjNGNmdJbDVPaWJtYWZ4ZjlkOU1FSGc9PSIsInZhbHVlIjoiY2hyRDNwYVl4aVRQelhqSUk3RHpuU0VMN25BdjBJcXp6cnJQd0dSK3Q4YlIrSURGVFRRdnpNYlo5bVRSd3J4cnIwaUIwVkxMaUxXK1VySFE3Wkh6NmtcL0x5YTJ2ZHE3YUdVMnFncExyaW51VCtpVW1oNE95OURrbG14XC9mRDBMXC9jdHdDb2NMR3Z0RFwvcVh0U0FJeElxXC9JeFNNZkpsNUV1MFRCUzZyZklOQXc9IiwibWFjIjoiNjlhMWE4OWY3ZDcwMzc3OTA5YjMwYzdhOTI1MDg5MWZmOTdlZjNmMDllOWQ2Y2JiNTA5NzYzYjFlYjQzMWI1MyJ9). then sign up with any name and email and complete the flow.

**Comment by Bane-D** [comment]
Than you for the link. Asking my colleague with iPhone to check it out.

In general loading is shown only while we wait for you to approve access to camera and mic. Once approved the loading should not be shown. The CSS could not cause it. Well only some CSS rules could make the loading screen shown when it should not be needed, not otherwise.

I just checked the page to see if I can spot anything specific as is, however looks like I will need to wait for my colleague to check it out.

PS: The video that is shown on the page, requires you to get approval from our side first (before any use, dev or public) since that video is property of Ziggeo. One of the terms for using the same is also to be played back from our own system.

Regards,
Bane

**Comment by bymoe** [comment]
Thank you @Bane-D, Video shown currently on staging environment for testing, we're not using it.

But why would Ziggeo wait to approve access when It's already showing my cam and audio? If user didn't approve mac and cam it shouldn't show.

I'll be waiting for any updates.

**Comment by sambua** [comment]
Hello @ImSolitude , 

Seems issue is related to [Content Security Policy](https://developer.chrome.com/extensions/contentSecurityPolicy) , Link is for Chrome but the same is true for the Safari. Could you please add this code in your webpage ?

```
<meta http-equiv="Content-Security-Policy" content="img-src * http:, https:, blob:, data:; media-src wss:, ws:, https:, https:, blob:; default-src * data: blob: ws: wss: gap://ready file://*; connect-src * ws: wss:;">
```
`*` can be changed into domain names, like `ziggeo.com` 

thanks in advance.

**Comment by bymoe** [comment]
@sambua Thank you,

Meta tag you sent break my site styles and I am getting this error,
![error](https://user-images.githubusercontent.com/20565199/87417842-67e72c80-c5d9-11ea-8bec-721f74004123.png)

**Comment by bymoe** [comment]
Adding `'unsafe-inline'`,

```
<meta httpEquiv="Content-Security-Policy" content="img-src * http:, https:, blob:, data:; media-src wss:, ws:, https:, https:, blob:; default-src * 'unsafe-inline' data: blob: ws: wss: gap://ready file://*; connect-src * ws: wss:;"></meta>
```
Getting this error 
![error](https://user-images.githubusercontent.com/20565199/87419371-0b394100-c5dc-11ea-8710-c24fce13e9b5.png)

**Comment by sambua** [comment]
`<meta http-equiv="Content-Security-Policy" content="default-src 'self';connect-src * wss:;">`

Could you please just add, above content. We need access only access for `wss://wowza.ziggeo.com/webrtc-session.json` 

here could be [some issues](https://github.com/w3c/webappsec-csp/issues/7), just need play on this to be able it work

**Comment by bymoe** [comment]
Thank you @sambua,

As you can see here https://imgur.com/a/hHELy3r, It didn't work. It's still stuck on loading for only iPhone.
If the above test link expired, use [this one](https://domaintestaccount.elevatustesting.xyz/video/assessment/eyJpdiI6IjYzd2lMNVVZM3pLc05MQkFLXC9uK1VRPT0iLCJ2YWx1ZSI6IjR5TnFhckhpV05sUE5uTExnRG10blVWWFpSRkVoY1VDaVRBR0s5N0pidm13RjRNRDNCcEhJUVwvUzIyUEhYbjVld1dqWUtQSkJjYzZTNmxtVnJHUnNEeWt6U2VcL1R1SHNvTVBkRGlMcFlONTB2TzFiZU12dUxHR0trMm1kcU54aGhEOGJaXC96QXUwVHZzamVOazJLOXk2emtPcTJObFdzSWdHejRQczk4STVVRT0iLCJtYWMiOiJlODk2M2ZhMDExNzc5MGFiMmQyNjY5NmE2NTk1YjQ2OTk4ODVmODExZTM1OTdlMTdiYzY4YzY0MGNkM2MwZWRhIn0=) instead.

**Comment by sambua** [comment]
Hello @ImSolitude , 

seems this issue is related to Gatsby itself, here's [open issue](https://github.com/gatsbyjs/gatsby/issues/10890) . Also I didn't check you can try [package](https://www.npmjs.com/package/gatsby-plugin-csp)
