### ISSUE TITLE
Prerelease version warning

### ISSUE THREAD

**Issue by zamirkhan** [Ziggeo/react-ziggeo#72]
We were using verion `4.0.5` of this package and getting the warning below in the console. After upgrading to `4.3.2`, we still get the message. What version of this package is recommended for production?

`You are currently using a prerelease version of the Ziggeo JS SDK. We suggest using the stable revision for production use, and prereleases for staging environments and tests only.`

**Comment by Bane-D** [comment]
Hi Zamir,

The warning you are seeing is from our JS SDK that is being used. Our current stable is r35 and our pre-relase is r36. You can see more details about the revisions here: https://ziggeo.com/docs/sdks/javascript/version-history

Now any time the r36 is used it will show the warning.

So if you check out the following: https://github.com/Ziggeo/react-ziggeo/blob/master/src/index.js#L3 it shows that your version of the client SDK would actually determine if you have some parameters / features available or not, as well as if you might see the pre-release message.

So for now, that would mean that you should grab the latest r35 instead from: https://github.com/Ziggeo/ziggeo-client-sdk/releases/tag/v2.35.22

* Please note that anything released in r36 will not be available if you switch to r35.

Regards,
Bane

**Comment by zamirkhan** [comment]
Thank you. What is unclear to us is how do we set which version of the SDK is used? We do not explicitly reference the SDK. Is this something we set in our code, or within our Ziggeo account/dashboard? If you could please provide us instructions on how to always point to the `stable` version, that would be great.

**Comment by Bane-D** [comment]
That is actually done by the line I referenced here: https://github.com/Ziggeo/react-ziggeo/blob/master/src/index.js#L3 and through the package.json file as seen here: https://github.com/Ziggeo/react-ziggeo/blob/master/package.json#L76

Unfortunately the versions do not work in such way that would allow you to put "stable", so you would have to manually change revisions.

The r35 has been switched to our `stable` tag just recently, so it will stay there for a while. So what you could do is to change
```"ziggeo-client-sdk": "^2.36.5"```
to something like
```"ziggeo-client-sdk": "~2.35.22"```
* In the above referenced package.json file.

What this would do is to install the 2.35.22 which is currently the latest stable revision (we might have more updates to it over time) and the ~ part will not allow you to skip over to r36 or higher, so it will stay there.

You would of course need to keep an eye out for when to move the version up.

Again, some features will not be available if you are using the stable tag and looking at the most recent feature as those are usually within some of the latest revisions.

Hope this helps :)

**Comment by zamirkhan** [comment]
Thanks @Bane-D . I guess my suggestion would be for this package to be pointing to whatever the "stable" version is at the time of updating and let people modify/rebuild to point to a newer release if they need it (rather than the opposite, which currently appears to be the case). It doesn't seem right for the default package installation to raise a warning when it's avoidable.

**Comment by Bane-D** [comment]
Hi Zamir,

I can definitely see the benefit of using our "stable" tag however also the benefit of using our non "stable" tag. The reason why I write as "stable" is because all of the codes that are released did pass tests. Manual tests as well as the automated tests to confirm that everything behaves as expected.

The tag we use "stable" does not really say that all other revisions are not stable, rather that this one will be automatically updated for you (moved from for example r30 to r35 to r38, etc.), allowing you to use it and have things updated and working automatically.

This is generally useful for people that want to have things working and do not really care about testing each revision and how the changes might possibly affect them.

With that said, I did bring this up and decision is made to going forward use the stable tag. We will be updating the SDK as we do so far, so that anyone can switch the revision manually however it will use the stable tag in the package.json file.

I do recommend making the change manually at this time because we will need to make this as a switch that makes sense and would not really stop anything from working for our customers.

**Comment by sambua** [comment]
fixed with https://github.com/Ziggeo/react-ziggeo/commit/746c037b0a42ed1eb06ca20faba5c32b2513309f
