### ISSUE TITLE
ReactZiggeo fails to compile due with in strict mode

### ISSUE THREAD

**Issue by Hamdan85** [Ziggeo/react-ziggeo#73]
https://support.ziggeo.com/hc/en-us/requests/431973

**Comment by sambua** [comment]
Hello, 

if don't include library where `use strict` is included there're no issue at all. Our Ziggeo JS SDK library not supporting use strict as it has to still support older browsers like IE8.

**Comment by Hamdan85** [comment]
Guys, turning strict mode off is a really bad practice. If the case is
supporting ie8, you should check for it and work it around.

We can't turn this off. This would bring security flaws and ultimately the
linter failing at the good standard practices.

So your suggestion is to not use the library... Did I get it right?

**Comment by sambua** [comment]
We check all our libraries with linter compilers and fix if it tell us we're using bad practice, from our side there should not be any security issue. We also very sensitive for security cases.

**Comment by Bane-D** [comment]
Hi there,

I just wanted to add up to what my colleague mentioned. We do not support strict mode on our SDK in order to allow people with different projects to compile and use our system.

The strict mode in itself does not really improve your security. It is there to allow you to notice if something seems to be wrong. If it is and you react to it, then it does affect your system security through your changes.

More so it is only being activated for development, not for production for same reasons - since some messages it puts out can be safely ignored.

>Strict mode checks are run in development mode only; they do not impact the production build.

With that said, I do want to mention that we do not have it on our roadmap to add support for strict mode especially since most of our customers are not really using it. As my colleague said, we do run lint and other such "systems" to allow us to detect replace and notify us of anything being off. We can not release a revision without that step passing on our side.

So this leaves us with few options:
1. For you to add ziggeo.js and ziggeo.css files directly and use our system directly as HTML tags on your pages avoiding any react compile and alike.
2. Set strict on specific points of your code ie not using strict with our code.

Here is an article on strict mode: https://reactjs.org/docs/strict-mode.html

Hope this helps, and I will mark this as closed at this time as per the above.

**Comment by Hamdan85** [comment]
Just a clarification:
The fact that you get noticed that you did something wrong is essentially a
security measure. It's there, among other, for this reason.

You really should consider duplicate the codebase if that's the case.

Thanks.

**Comment by ksafranski** [comment]
This seems like a pretty big issue as now we're blocked from support ESM purely due to this library. From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)

> Using with is not recommended, and is forbidden in ECMAScript 5 strict mode. The recommended alternative is to assign the object whose properties you want to access to a temporary variable.

**Comment by Bane-D** [comment]
Hi, thank you for raising this as an issue.

This is known and something we can not remove at this time. The reason for the error is because we have support for old browsers within our system, hence there being a requirement for some specific codes to be present.

Since our r37 is dropping the support for Flash and in turn for any non modern browsers (such as IE8) that can only use Flash, once our stable tag starts pointing to r37 or above we will be able to work on this as we would be dropping some older codes.

You can see more info about our revisions here: https://ziggeo.com/docs/sdks/javascript/version-history
* Our revision currently provided under stable tag is r36 and our latest at this moment is r38.

Hope this helps.

**Comment by ksafranski** [comment]
so for now the only option for us is to either _not_ use ESM modules or build out from scratch through aquiring the Ziggeo SDK outside scope of our main import?

**Comment by ksafranski** [comment]
I've converted to use the vanilla JS SDK and have the following:

```javascript
export default function App() {
  useEffect(() => {
    var ziggeoApp = new ZiggeoApi.V2.Application({
      token: "..."
    });
    ziggeoApp.on("ready", function () {
      var recorder = new ZiggeoApi.V2.Recorder({
        element: document.getElementById("ziggeo_recorder"),
        attrs: {
          tags: ["test-video"],
          width: "100%",
          height: "55vh",
          theme: "modern",
          videoprofile: "336bb778db59f53a622cd85979e99469",
          allowmultistreams: true,
          recordingwidth: window.innerWidth < 1024 ? window.innerWidth : 1920,
          recordingheight: window.innerHeight < 800 ? window.innerHeight : 1080,
          picksnapshots: false,
          videobitrate: 8000
        }
      });

      recorder.activate();

      recorder.on("uploading", () => {
        console.log(">>>> UPLLOADING");
      });
      recorder.on("verified", (embed) => {
        console.log("!!!!", embed);
      });
    });
  }, []);
  return (
    <div className="App">
      <div id="ziggeo_recorder"></div>
    </div>
  );
}
```

This renders fine, records and logs when it's uploading, however, the second event `verified` isn't giving me an argument back. When using the react component the `onVerified` method returned an `embed` object which had a `video` prop we stored, then used in the player to get the video. Am I missing something here or is there a different event that gives us that property back?

**Comment by Bane-D** [comment]
I am not working on React implementation as I am not too familiar with it. I am saying this because there might be some use cases that require some specific implementation. So the actual way for implementation might be best checked by yourself (what would work for you).

Per my own understanding, the React's strict mode only affects development side and is used to help find issues before they are released to production. It will not however remove our script or forbid you from using it in production.

Using the implementation as you did should work as well.

In regards to `verified` event. We have 2 types. One that fires on specific embedding (and this one will not return embedding object), and another that fires for all embeddings and that one returns the embedding object as well.

Per embedding (private) events can be seen here: https://ziggeo.com/docs/sdks/javascript/browser-interaction/events

Application wide (on same page) events would be handled as explained here: https://ziggeo.com/docs/sdks/javascript/browser-interaction/application-embedding-events

So in your case you would just slightly change your code from:
```
      recorder.on("verified", (embed) => {
        console.log("!!!!", embed);
      });
```

to:
```
      ziggeoApp.embed_events.on("verified", (embed) => {
        console.log("!!!!", embed);
      });
```
As you do it will work just as you wanted :)

**Comment by Bane-D** [comment]
Oh and while likely obvious, just being safe and adding more info:

`ziggeoApp.embed_events.on` is created per:

```
var ziggeoApp = new ZiggeoApi.V2.Application({
...
```
So if you initialize your app in a different way, you would need to use a different reference for events.

**Comment by ksafranski** [comment]
Thanks, that seems to get me the response object, though looking through it I can't find the video id (token) to reference it. Any idea how to get that so I can save it on our end?

Also, the `with` issue is blocking from a dev standpoint - I can't build in an environment using esm (we're switching from webpack to vite) and with new bundlers moving toward esm I feel you guys may run into this more. Not a big deal, the solution I threw together is a pretty 1:1 transition from the actual component.

**Comment by Bane-D** [comment]
Ah I see. So again I am not too familiar with React however we are generally looking to make the updates as needed (to support latest trends) and also to support our customers using older technologies. Unfortunately IE is still being used.

With the move of our stable tag we will however be able to remove all such codes that are not needed.
We also welcome adding such and any other feature requests on our https://feedback.ziggeo.com pages :)

Going back to getting the video details. You can actually do that quite easily by using the following:
```
    ziggeoApp.embed_events.on("verified", (embed) => {
        console.log("!!!!", embed);
        console.log(embed.get());
    });
```

* This will print out all of the object properties that you can also get by specifying directly. I think this might be more interesting hence writing it like that.

If you really only want the video, you would do it like so:
```
    ziggeoApp.embed_events.on("verified", (embed) => {
        console.log("!!!!", embed);
        console.log(embed.get('video'));
    });
```

**Comment by ksafranski** [comment]
Thanks! That got me the token so I'm basically fully replicating what I had with the React Component.

I totally understand the support issue, I guess I'm just not sure why `with` would be needed for compatibility; it seems like the opposite - where you're supporting something deprecated that could be done other ways just the same.

Anyways, not trying to argue, you guys have a lot to support. I appreciate the help (and especially on a weekend). Hopefully this issue serves someone else who gets stuck - all-in-all it was an easy rewrite since you guys really stuck to the same conventions between the native sdk and the component.

**Comment by Bane-D** [comment]
Glad to hear that it is working for you :) 

Also thank you for posting your code as it likely will help someone else as well.

In regards to the codes, some codes are no longer easily tested as they require some systems or devices that are harder to get at this time in which case it is easier to leave the working codes as they are ;)

Agreed if we did not want to provide long time support for our customers that would be easier to do, however "long time support" roles off your tongue in such a nice way ;)

**Comment by Bane-D** [comment]
Hi everyone,

I am following up to let you know that with our latest revision (of our JS SDK) we have removed the use of `with(object)` and the strict mode should be possible at this time.

Please feel free to check it out and see how it works for you.

For ReactSDK to use the latest revision, you would need to follow these steps: https://github.com/Ziggeo/react-ziggeo#upgrade-ziggeo-sdk

The version that includes this is: `2.41.2`.

**Comment by sryze** [comment]
@Bane-D I'm using 4.6.0 and still getting this error when compiling with Babel.

```
SyntaxError: node_modules\react-ziggeo\build\index.js: 'with' in strict mode. (11946:1221544
```

**Comment by Bane-D** [comment]
Hi Sergey, that is actually expected because the 4.6.0 uses r39: https://github.com/Ziggeo/react-ziggeo/blob/master/package.json#L76 what would be ideal is to upgrade to r40. That is to:
```
"ziggeo-client-sdk": "~2.41.2"
```

The steps needed when doing the upgrade of revision are explained here: https://github.com/Ziggeo/react-ziggeo#upgrade-ziggeo-sdk

Once you do, it should work :)

**Comment by sryze** [comment]
@Bane-D Thanks. Wouldn't it be easier to have `ziggeo-client-sdk` declared as a peer dependency? I'm not a pro at Node.js but I think that would allow users of `react-ziggeo` to switch between different versions of the SDK more easily.

**Comment by sambua** [comment]
Hello @sryze , thanks for your advice, yes, sure mention in peer dependency section `ziggeo-client-sdk` will be good just for case use correct version and we will add it in the next releases. But it's not affect package itself, as it's more informative section rather than version which will be installed and build based on that. 

P.S: This package is open source you're always welcome to improve it and send a new push requests if want to support us, thanks :)
