### ISSUE TITLE
How can I select a microphone or camera programmatically?

### ISSUE THREAD

**Issue by SungwooJo** [Ziggeo/react-ziggeo#74]
I found this post.
 
https://support.ziggeo.com/hc/en-us/community/posts/360038507774-Is-it-possible-to-set-default-camera-for-mobile-front-or-rear-camera-

According to the post, there seems to be a method to select camera, but I can't find it in the recorder 
received from onRef.

Can I select a microphone or camera programmatically?

**Comment by Bane-D** [comment]
Hi Jeff,

The parameter mentioned there can be used in react as well as `camerafacefront`.

In terms of the selecting camera by ID or any other function that you might find mentioned on our forum, and can not find at this stage, please check following pages.

For reference, when it comes to JavaScript, these pages are the main reference points:
https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters (for parameters)
https://ziggeo.com/docs/sdks/javascript/browser-interaction/methods (for methods you can call)
https://ziggeo.com/docs/sdks/javascript/browser-interaction/events (events you can listen to)

All functions that are added and would stay are shown here. At some time we might have some additional functions available, however if they are not added to our official pages, they might have been renamed or completely removed.

In general there is no benefit of allowing ID to be used to switch the camera. Your code would not really be able to know what ID will do what, if that is needed and what the switch resulted in.

What we suggest is for your end user to just go to the recorder. Our system will use the default system camera as reported by the system itself. This is generally the best approach and just works for all.

Now some people will have multiple cameras. Our system will also list the other cameras in the list, so that they can switch through them (if they have multiple cameras).

Our system will also grab the names of the camera as provided by underlying system, so they have a much better user experience and can actually see what they are selecting and what is happening.

Of course, happy to better understand why you would like to be able to switch the ID from your code. Maybe there is some interesting use case.
