### ISSUE TITLE
Video recording submitted even if  "Confirm video" button is not clicked (Manual Submit)

### ISSUE THREAD

**Issue by saransh-dhama** [Ziggeo/react-ziggeo#76]
When manualsubmit enabled, recorder sends a submit call to server even before this "Confirm video" button is clicked. If a user records his video but chooses not to click on confirm video, video is still saved.

**Comment by ntshcalleia** [comment]
Hi @saransh-dhama, thanks for reaching out. Yes, you're correct, the video will still be submitted even if the user doesn't click on the confirm button. That is the expected behaviour.

What _manualsubmit_ does is allow you to know if the user has confirmed the video (ie if they're happy with their video), then you can listen for the _onManuallySubmitted_ event to be able to respond to their feedback.

If you're saving video tokens on your own database, for example, you could choose to only save video tokens after the _onManuallySubmitted_ event is triggered.

Or, if you don't want to keep videos that weren't confirmed, you could set [_expiration days_](https://github.com/Ziggeo/react-ziggeo/blob/746c037b0a42ed1eb06ca20faba5c32b2513309f/src/constants.js#L47) to 1 and then, if _onManuallySubmitted_ is triggered, update the video to remove expiration date. 🙂

Another way people use _manualsubmit_ + _onManuallySubmitted_ is to change pages or display a "thank you" message on the screen.
