### ISSUE TITLE
Change language on Ziggeo

### ISSUE THREAD

**Issue by Abdulrohman-Alakrad** [Ziggeo/react-ziggeo#79]
How to change language on ZIggeo, if there is any tags for this ?

**Comment by ntshcalleia** [comment]
Hi there! I'm assuming the issue was closed because you found the solution, but I'll write it here in case someone with the same question finds this page. To change the language on Ziggeo you can use the locale parameter:

```jsx
<ZiggeoRecorder
        ...
        locale={'language_shortcode'}
/>
```

The full list of supported languages can be found here:
https://ziggeo.com/features/language-support

If you need to change one or two strings of text you can use the following snippet:
```javascript
 mediaLocales={[
    {
        register: {"ba-videorecorder-chooser.record-video": "Rec"}, // Any object you want to touch
        priority: 10 // Optional, default is 10.
    },
]}
```

And this is where you can find the full list of string keys and translations:
https://ziggeo.com/docs/sdks/javascript/browser-integration/localization
