### ISSUE TITLE
React ready_to_play event

### ISSUE THREAD

**Issue by milosmoto** [Ziggeo/react-ziggeo#8]
Can you provide for React ZiggeoRecorder this:

ready_to_play
Triggered when a video play is ready to play a video

Example:
```
ZiggeoApi.Events.on("ready_to_play", function ( data ) {
    //Your code goes here
});
```

**Comment by Bane-D** [comment]
Hi Milos,

Just posting here that this event (ready_to_play) is available since our r29 revision, which is still in developer preview state. Once r29 gets published officially we would be adding it to our SDKs as we add other features that r29 brings :)

So for now it is not available, however it will be part of the React SDK soon.

* We are adding new revisions to our JavaScript SDK that is used by React and in each you can find some event, property or method that was just added and this is one of such events.

* Keeping it open to update once it is available.

Regards,
Bane

**Comment by Bane-D** [comment]
Hi Milos,

This was missed, however r29 was released and currently we have r32 as well. Using any of the same the `ready_to_play` will be available for you.

I will close this down for now, however if you have any questions for us, just let us know :)

Regards,
Bane
