### ISSUE TITLE
"Choose screen to share" popup shows up when `reset` method is called

### ISSUE THREAD

**Issue by ronnaf** [Ziggeo/react-ziggeo#87]
Hi!

Is the "Choose screen to share" popup supposed to show up if the `reset` method is called? The flow is a bit weird since it's a reset, what purpose would it have to display the popup? Is there a way to bypass this? I'm trying to achieve a "silent" reset. 

Some code snippet:
```tsx
const [recorderRef, setRecorderRef] = useState<any | null>(null);

const reset = () => {
    recorderRef?.reset();
};

...
<ZiggeoRecorder
    onRef={(ref: any) => setRecorderRef(ref)}
    ...
/>
```

Thank you!

**Comment by Bane-D** [comment]
Hi Ronna,

That would depend on other parameters you use. You are likely using skipinitial in your code, which skips the first screen giving you options to use.

In such case, you might prefer using `.destroy()` over `.reset()` since that would destroy the current recorder and allow you to create a new one once you are ready for it.

Generally the same happens, however you would need to create it with all the event handlers again.

Alternatively, if consider not using the skipinitial parameter.

Let us know if that helps :)
