### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by KonstantinSimeonov** [Ziggeo/react-ziggeo#93]
We're using `react-ziggeo` and we got sentry reports for the `Cannot read properties of undefined (reading 'push')` error. The source maps point to this piece of code (which I couldn't find here or in `ziggeo-client-sdk`):

```js
ziggeo-client-sdk - v2.39.16 - 2022-01-24
Copyright (c) Ziggeo
Closed Source Software License.
*/
{snip} aAvailable:function(e){e.data&&0<e.data.size&&this._chunks.push(e.data)},_dataStop:function(e){var t,i;this._data=new Blob(this._chunks,{typ {snip}
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(128), __webpack_require__(333)(module)))
/***/ }),
/* 335 */
/***/ (function(module, exports, __webpack_require__) {
```

Sentry breadcrumbs:

```
xhr
POST https://embed-api.ziggeo.com/v1/applications/0c490a575790e4b3064a9d87e4d9af74/videos/videos-upload-url?_wrapstatus=true&_nocache=1660012823014 [200]
02:40:23
xhr
POST https://api-us-east-1.ziggeo.com/embed/v1/applications/0c490a575790e4b3064a9d87e4d9af74/scitylana/kcart?_wrapstatus=true&_nocache=1660012829472 [200]
02:40:30
xhr
GET [Filtered] [200]
02:41:35
exception
TypeError: Cannot read properties of undefined (reading 'push')
```

- OS: win/mac
- browser: chrome
- `react-ziggeo v4.6.0`

I'm not sure whether this is the place to open the issue or `ziggeo-client-sdk` would be more appropriate.

**Comment by Bane-D** [comment]
Hi Konstantin,

Thank you for reporting the issue.

Based on what you sent, it looks like it might be happening during the actual upload or once it finishes, however there is not really much info about it.

Based on the error I would guess that it is related to the React and not our JS SDK. To be safe, can you tell us the following:
1. Can you please let us know if you can recreate this yourself or if someone else might be able to recreate it repeatably?
2. Do you listen to `verified` (or `uploaded`) event(s) in your code?
3. If you can recreate this yourself and you listen to event such as `verified`, what happens if you remove the code that is within the same - ie does that help remove the issue for you?

**Comment by KonstantinSimeonov** [comment]
I'll investigate those and get back to you, thanks for the quick response!

**Comment by KonstantinSimeonov** [comment]
I wasn't able to reproduce it, but I have a few other reproduction ideas which I've yet to try.

basically, this is what we're doing (so for 2, yes, we're listening to those events):

```ts
      <ZiggeoRecorder
        allowupload={allowUpload}
        apiKey={ziggeoToken}
        height={height || "100%"}
        onProcessed={onVideoProcessed}
        onProcessing={onVideoProcessing}
        onRecording={onVideoRecording}
        onUploaded={onVideoVerified}
        onUploading={onVideoUploading}
        onVerified={onVideoVerified}
        picksnapshots={false}
        width={width || "100%"}
      />
```

I'll add more details later (1 & 3).

**Comment by Bane-D** [comment]
OK, thank you Konstantin.

It would be great if the person that reported the issue could test on the identical recorder without listening to those events, just to be safe (if you can not recreate it).

If you manage to recreate it yourself of course, that would be ideal as we could then get more details in regards to the same.

Looking forward to your update.

**Comment by Bane-D** [comment]
Hi Konstantin,

My colleague found what should be the source of the error that you have mentioned. The thing is that this part of code can cause such error only in very few specific cases:
1. Your code / workflow had removed the recorder before the data (video) was completely uploaded
2. The end user had clicked on something to remove the recorder before the video was completely uploaded

If the video comes to verified event, the same is already uploaded, so that would not fire.

This would mean that either something is present in `onRecording`, or `onUploading` that can remove the recorder, or the end user can do the same in some other ways.

* Sharing this in case it helps you when looking on the page to spot anything that can do what I mentioned above and that matches your issue report.

**Comment by KonstantinSimeonov** [comment]
Yep, unmounting the recorder while it's recording reproduces the issue. We'll be working to fix that on our end. If you're not planning to fix this, this issue can be closed.

**Comment by Bane-D** [comment]
Hi Konstantin,

Yes, that is the expected time when such error could happen. The best would be to see when or how that is possible to happen in your workflow so that you avoid someone recording and switching to a different state on your side.

In terms of a fix, this is an unexpected way to use our recorder and is not really a bug. That is, said differently, the error shows that something happened that was unexpected and allows for you to now correct anything in your workflow that leads to this unwanted scenario.

As such I will close this, however we are considering that instead of having an error we raise a more descriptive error in such case, so going forward it is easier to know why that happens.

Please do of course reach out to us if you have any additional questions for us :)
