### ISSUE TITLE
ask: how to trigger reload the video with subtitle when clicking a button?

### ISSUE THREAD

**Issue by clement-lta** [Ziggeo/react-ziggeo#95]
Hi! Thanks for providing a good lib!

I have a Player and when I call the API to generate subtitles for this video, I need to reload and play the video with subtitles.
But for now, I can not find any method to reset this video. Can you help me?

**Comment by Bane-D** [comment]
Hi Clement,

I want to start with the fact that the extraction of the subtitles is not instant. Because of this, if you are playing the video right after it is uploaded at that time the subtitles will not be available.

After some time has passed our system would send a webhook (if you have set it up) to notify you of the audio transcription being available. Before this happens, you can reload the player as many times as you wish, it will not show you subtitles.

Now with that said, I do want to offer suggestion and will attempt to hopefully answer your question :)

**Suggestion**

What I would suggest is to add the following [parameter](https://ziggeo.com/docs/sdks/javascript/browser-integration/parameters/) to your player: `audio-transcription-as-subtitles`.

When this is set (as true) your player will load up the subtitles when they are available. So at any point after the webhook fires that the audio transcription is available any page load with the player will load the video data including the subtitles. It will then also show the same.

**How to**

Now there might be usecases when you want to wait for this to happen and then update the page with the player to automatically switch to show the player with the subtitle.

This would be a bit more complex and will involve different points, so I will just provide you with the general outline.
You would (option 1):
1. Need to set up a webhook in order for your server to know once the audio transcription is available
2. have AJAX calls to be set on the page with player to ping your server to see if the audio transcription is available
3. Set up the player on the page to include the `audio-transcription-as-subtitles` parameter set as true
4. Once the value is returned that the audio transcription is available you can make a JS call such as `player.reset()` ([see more here](https://ziggeo.com/docs/sdks/javascript/browser-interaction/methods/)) which will reload the video

For option 2 you would:
1. Need to use our [JS API](https://ziggeo.com/docs/sdks/javascript/api/) to ping our servers in some interval to get the video data
2. Once the audio transcription is available, you would have the very same steps as above starting with step 3.

The difference between the two would be that the option 1 would listen and get notified once our server has new info while the option 2 would be more about you pinging our system constantly to possibly get a new value.

Both are OK, however the second could result in retrieving cached object returned to you depending on your browser, OS, network setup or ISP as repeatedly making same calls that result in same value is often cached by different parts of network to save bandwidth.

Hope this helps :)

**Comment by clement-lta** [comment]
Hey @Bane-D 
Thank you so much!
