### ISSUE TITLE
Player: onError callback is not fired when trying to acces video that doesn't exist

### ISSUE THREAD

**Issue by humanamburu** [Ziggeo/react-ziggeo#98]
Hello,

We would like to show an error placeholder when user tries to access video that doesn't exist (or have a fallback if token is not configured correctly), but now `react-ziggeo` ZiggeoPlayer (4.6.2) doesn't trigger `onLoad` or `onError` callback when 403 error happened.

In the example below I mocked the `video` token and `onErrror` callback has not been called. 

```tsx
import React, { useEffect, useState } from 'react'
import { ZiggeoPlayer } from 'react-ziggeo'

import { VideoError } from './VideoError'

export const VideoPlayer = ({
    videoToken,
    themecolor = 'black',
    width = '100%',
    preventReRenderOnUpdate = false,
    height,
    apiKey,
    onLoaded,
    onError
}): ZiggeoPlayer => {
    const [error, setError] = useState(null)

    if (error) {
        return <VideoError />
    }

    return (
        <ZiggeoPlayer
            key={videoToken}
            apiKey={apiKey}
            {/* video token is not correct below on purpose*/}
            video={'1'}
            theme="modern"
            themecolor={themecolor}
            width={width}
            height={height}
            preventReRenderOnUpdate={preventReRenderOnUpdate}
            onLoaded={onLoaded}
            onError={(error) => {
                {/* this callback is not called*/}
                setError(error)
                onError && onError(error)
            }}
        />
    )
}
```

Could you please help me with this issue?

**Comment by Bane-D** [comment]
Hi there,

Thank you for reporting this. This is actually not happening because of anything in this React SDK, rather in our JS SDK (https://github.com/Ziggeo/ziggeo-client-sdk/). At this time, we are not raising an error event in the cases that you have mentioned.

That said, it does seem like a good idea to add, so we have added a ticket for ourselves to introduce this change to our JS SDK.

* Once the change is added there, it will be available from some specific revision. After that is done, it would be made available within the React SDK.

**Comment by humanamburu** [comment]
Thank you for the quick response!
